//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp
    {
        public int EId { get; set; }
        public string EName { get; set; }
        public string Ezhiw { get; set; }
        public string ETime { get; set; }
        public int Ejiben { get; set; }
        public int Ejiangjin { get; set; }
        public string Eddre { get; set; }
        public int DId { get; set; }
    
        public virtual dept dept { get; set; }
    }
}
